# Generated by Django 2.2.3 on 2019-07-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('cv', models.FileField(upload_to='files')),
                ('job', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=40, null=True)),
                ('skills', models.CharField(max_length=40, null=True)),
                ('experience', models.CharField(max_length=40, null=True)),
                ('contact', models.CharField(max_length=40, null=True)),
                ('location', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
