# Generated by Django 2.2.3 on 2019-07-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='cv',
            field=models.FileField(upload_to='files/'),
        ),
    ]
