# Generated by Django 2.2.3 on 2019-07-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20190728_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='cv',
        ),
    ]
