# Generated by Django 2.2.3 on 2019-07-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_remove_register_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='cv',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
    ]
